### ISSUE TITLE
Use an identifier (magic number) ?

### ISSUE THREAD

**Issue by IurmanJ** [evyncke/opsec-probe-attribution#6]
Robert Story:

> On the in-bound approach have you thought about putting some identifier in the packet so that wireshark/tcpdump could identify it? The fact networks could filter these out could be considered a feature, you can normally opt out of this sort of research problem.

**Comment by evyncke** [comment]
As discussed, this could add complexity for little benefit.

**Comment by IurmanJ** [comment]
This is discussed in the document.
