### ISSUE TITLE
Ron Bonica's comment

### ISSUE THREAD

**Issue by IurmanJ** [evyncke/opsec-probe-attribution#7]
Ron: consequence could be that network operators filter packets containing the URI. The reason is simple: there is no/low benefit for them to participate in the probe experiment and also because there might be risks involved for them --> all of this may bias the results

**Comment by evyncke** [comment]
This is even a good thing as this in-band 'tag' could be used by SP.

Rather leave the text unchanged ?

**Comment by IurmanJ** [comment]
This is discussed in the document.
